//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good
        ///new
        ///first
        ///last
        ///long
        ///great
        ///little
        ///own
        ///other
        ///old
        ///right
        ///big
        ///high
        ///different
        ///small
        ///large
        ///next
        ///early
        ///young
        ///important
        ///few
        ///public
        ///bad
        ///same
        ///able.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nice
        ///good
        ///fast
        ///just
        ///more
        ///well
        ///always.
        /// </summary>
        internal static string adverbs {
            get {
                return ResourceManager.GetString("adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///an
        ///the.
        /// </summary>
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///but
        ///or
        /////nor
        /////yet
        ///so.
        /// </summary>
        internal static string coordinating_conjunctions {
            get {
                return ResourceManager.GetString("coordinating_conjunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both/and
        ///not only/but also
        ///either/or
        ///neither/nor
        ///as/as
        ///such/that
        ///as many/as.
        /// </summary>
        internal static string correlative_conjunctions {
            get {
                return ResourceManager.GetString("correlative_conjunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time
        ///people
        ///year
        ///way
        ///day
        ///thing
        ///man
        ///world
        ///life
        ///ocean
        ///part
        ///child
        ///tree
        ///woman
        ///place
        ///work
        ///case
        ///point
        ///love
        ///happines
        ///group
        ///fact.
        /// </summary>
        internal static string nouns {
            get {
                return ResourceManager.GetString("nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as
        ///but
        ///for
        ///from
        ///like
        ///than
        ///to
        ///with.
        /// </summary>
        internal static string prepositions {
            get {
                return ResourceManager.GetString("prepositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I
        ///he
        ///she
        ///it
        ///we
        ///you
        ///they.
        /// </summary>
        internal static string pronouns {
            get {
                return ResourceManager.GetString("pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-&gt;NP VP
        ///NP-&gt;C CNP
        ///CNP-&gt;ADJ CNP
        ///CNP-&gt;N
        ///NP-&gt;NP U NP
        ///VP-&gt;VP WH S
        ///VP-&gt;V
        ///VP-&gt;V CNP
        ///
        /////C CNP VP WH S =&gt; VP WH S.
        /// </summary>
        internal static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after
        ///although
        ///as
        ///before
        ///if
        ///while.
        /// </summary>
        internal static string subordinating_conjunctions {
            get {
                return ResourceManager.GetString("subordinating_conjunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have
        ///say
        ///get
        ///make
        ///go
        ///know
        ///take
        ///see
        ///come
        ///think
        ///look
        ///want
        ///give
        ///use
        ///find
        ///tell
        ///ask
        ///work
        ///feel
        ///try
        ///leave
        ///switch.
        /// </summary>
        internal static string verbs {
            get {
                return ResourceManager.GetString("verbs", resourceCulture);
            }
        }
    }
}
